### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by justinpusherlove** [jxhuang0508/CVRN#5]
Thanks for your great job！I followed the instrution to run the instance segmentation branch with one GPU ：TITAN XP(12GB), but it soon got out of memory, can you guide me what's the matter with it？Thanks in advance.

2022-02-06 13:35:05,877 | optimizer.py | line 59 : {'lr': 1, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0.0005, 'nesterov': False}
loading annotations into memory...
Done (t=21.05s)
creating index...
index created!
loading annotations into memory...
Done (t=11.43s)
creating index...
index created!
Filtered roidb entries: 5950
len_source_loader: 16556
len_target_loader: 5950
2022-02-06 13:37:34,389 | callback.py | line 40 : Batch [20]	Speed: 0.32 samples/sec	Train-rpn_cls_loss=0.613139,	rpn_bbox_loss=0.335659,	rcnn_accuracy=0.761426,	cls_loss=0.779723,	bbox_loss=0.249559,	mask_loss=0.750133,	
2022-02-06 13:37:36,418 | callback.py | line 40 : Batch [20]	Speed: 9.86 samples/sec	Train-rcnn_sida_loss=0.009439,	mask_sida_loss=0.097951,	
Traceback (most recent call last):
  File "upsnet/train_seed1234_co_training_cross_style.py", line 447, in <module>
    upsnet_train()
  File "upsnet/train_seed1234_co_training_cross_style.py", line 360, in upsnet_train
    output = train_model(*batch_target)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "upsnet/../lib/utils/data_parallel.py", line 110, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "upsnet/../upsnet/models/resnet_upsnet_multiscale_branch_lr10.py", line 300, in forward
    mask_score_sc = self.mask_branch([fpn_p2_sc, fpn_p3_sc, fpn_p4_sc, fpn_p5_sc], rois_sc)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "upsnet/../upsnet/models/rcnn.py", line 85, in forward
    mask_deconv1 = self.mask_deconv1(mask_conv4)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 691, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA error: out of memory

**Comment by jxhuang0508** [comment]
Hi,

For 'CUDA error: out of memory' issue, you may use the GPU with larger memory size, or decrease the input image size, or decrease the network size.

Jiaxing

**Comment by justinpusherlove** [comment]
Thanks for your response, can you tell me the GPU and backbone you used in your experiment? Since I've tried to follow the paper to get the results, so 2080ti(11GB) is  used to run the resnet101, but it will cause the error: cuda out of memory.

**Comment by jxhuang0508** [comment]
I used Tesla V100 GPU (32GB) for retraining when I clean the code. As far as I can remember, the GPU memory usage is about 12~14 GB, which means the provided code can not support GPU with memory < 16GB. I suggest to use Tesla V100 GPU (32GB) for reproduction as it does not require modifications of current code.

Jiaxing

**Comment by justinpusherlove** [comment]
Thank you so much!
